import * as vscode from 'vscode';
import { NoteGraph } from './noteGraph';

// ─── Types ────────────────────────────────────────────────────────────────────

interface GraphForces {
  repulsion: number;
  gravity: number;
  edgeLength: number;
  damping: number;
}

/** Keyed by note display-name (filename without .md). */
type GraphPositions = Record<string, { x: number; y: number }>;

interface GraphViewport {
  zoom: number;
  panX: number;
  panY: number;
}

interface GraphSettings {
  forces: GraphForces;
  positions: GraphPositions;
  viewport: GraphViewport;
}

// ─── Defaults ─────────────────────────────────────────────────────────────────

const DEFAULT_FORCES: GraphForces = {
  repulsion: 8000,
  gravity: 0.15,
  edgeLength: 150,
  damping: 0.5,
};

const DEFAULT_VIEWPORT: GraphViewport = {
  zoom: 1.0,
  panX: 0,
  panY: 0,
};

const DEFAULT_SETTINGS: GraphSettings = {
  forces: DEFAULT_FORCES,
  positions: {},
  viewport: DEFAULT_VIEWPORT,
};

// ─── JSONC helpers ────────────────────────────────────────────────────────────

/** Strip // line-comments and /* block-comments before parsing. */
function parseJsonc(text: string): GraphSettings {
  const stripped = text
    .replace(/\/\/[^\n]*/g, '')          // remove // … line comments
    .replace(/\/\*[\s\S]*?\*\//g, '');   // remove /* … */ block comments
  return JSON.parse(stripped) as GraphSettings;
}

/** Serialise settings to a commented JSONC file that is easy to read and edit. */
function formatSettingsFile(settings: GraphSettings): string {
  const f = settings.forces;
  const v = settings.viewport;
  const posLines = Object.entries(settings.positions)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, pos]) => {
      const x = +pos.x.toFixed(2);
      const y = +pos.y.toFixed(2);
      return `    "${name}": { "x": ${x}, "y": ${y} }`;
    })
    .join(',\n');

  return [
    '// Code Nodes — Graph Settings',
    '// ─────────────────────────────────────────────────────────────────────────────',
    '// Auto-generated by the Code Nodes VS Code extension.',
    '// Safe to edit by hand. Delete this file to reset everything to defaults.',
    '// Changes take effect the next time the graph panel is opened.',
    '{',
    '',
    '  // ── Physics sliders ──────────────────────────────────────────────────────',
    '  // These mirror the sliders in the graph panel; editing here or dragging the',
    '  // sliders both update this file.',
    '  //   repulsion  — how strongly nodes push each other apart (higher = more space)',
    '  //   gravity    — pull toward the graph centre (lower = nodes spread further out)',
    '  //   edgeLength — ideal pixel distance between connected nodes',
    '  //   damping    — energy applied when the layout re-settles after a change',
    '  //                (0 = frozen in place, 1 = full recompute)',
    '  "forces": {',
    `    "repulsion":  ${f.repulsion},`,
    `    "gravity":    ${f.gravity},`,
    `    "edgeLength": ${f.edgeLength},`,
    `    "damping":    ${f.damping}`,
    '  },',
    '',
    '  // ── Node positions ────────────────────────────────────────────────────────',
    '  // Saved (x, y) coordinates for each note, keyed by filename without ".md".',
    '  // The graph restores these on open so your manual layout is preserved.',
    '  // Delete just this "positions" block (or set it to {}) to reset the layout.',
    '  "positions": {',
    posLines,
    '  },',
    '',
    '  // ── Viewport ─────────────────────────────────────────────────────────────',
    '  // Camera zoom and pan position, restored when the graph panel is reopened.',
    '  //   zoom — magnification level (1.0 = 100 %, 0.5 = zoomed out, 2.0 = zoomed in)',
    '  //   panX / panY — pixel offset of the canvas origin from the panel top-left',
    '  // Delete this block (or set zoom: 1, panX: 0, panY: 0) to reset the view.',
    '  "viewport": {',
    `    "zoom": ${+v.zoom.toFixed(4)},`,
    `    "panX": ${+v.panX.toFixed(2)},`,
    `    "panY": ${+v.panY.toFixed(2)}`,
    '  }',
    '',
    '}',
    '',
  ].join('\n');
}

// ─── Settings file I/O ────────────────────────────────────────────────────────

const SETTINGS_FILENAME = 'graph_settings.jsonc';

function settingsUri(): vscode.Uri | undefined {
  const folder = vscode.workspace.workspaceFolders?.[0];
  return folder
    ? vscode.Uri.joinPath(folder.uri, SETTINGS_FILENAME)
    : undefined;
}

async function readSettings(): Promise<GraphSettings> {
  const uri = settingsUri();
  if (!uri) return { ...DEFAULT_SETTINGS, forces: { ...DEFAULT_FORCES } };

  try {
    const bytes = await vscode.workspace.fs.readFile(uri);
    const raw = parseJsonc(Buffer.from(bytes).toString('utf-8'));
    // Merge with defaults so missing fields never crash the extension
    return {
      forces:    { ...DEFAULT_FORCES,    ...(raw.forces    ?? {}) },
      positions: { ...(raw.positions ?? {}) },
      viewport:  { ...DEFAULT_VIEWPORT,  ...(raw.viewport  ?? {}) },
    };
  } catch {
    // File doesn't exist yet or is malformed — use defaults
    return { forces: { ...DEFAULT_FORCES }, positions: {}, viewport: { ...DEFAULT_VIEWPORT } };
  }
}

async function writeSettings(settings: GraphSettings): Promise<void> {
  const uri = settingsUri();
  if (!uri) return; // no workspace open — nothing to write
  const content = formatSettingsFile(settings);
  await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf-8'));
}

// ─── Misc ─────────────────────────────────────────────────────────────────────

function getNonce(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  return Array.from({ length: 32 }, () =>
    chars[Math.floor(Math.random() * chars.length)]
  ).join('');
}

// ─── Provider ─────────────────────────────────────────────────────────────────

export class GraphProvider {
  private panel: vscode.WebviewPanel | undefined;
  /** Last topology hash sent to the webview. Empty string forces a full layout on first open. */
  private lastTopologyHash = '';
  /** In-memory settings cache; kept in sync with the file. */
  private settings: GraphSettings = { forces: { ...DEFAULT_FORCES }, positions: {}, viewport: { ...DEFAULT_VIEWPORT } };
  /** Debounce timer for file writes. */
  private saveTimer: ReturnType<typeof setTimeout> | undefined;

  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly noteGraph: NoteGraph
  ) {}

  toggle(): void {
    if (this.panel) {
      this.panel.dispose();
      return;
    }
    this.show();
  }

  show(): void {
    if (this.panel) {
      this.panel.reveal(vscode.ViewColumn.Beside, true);
      return;
    }

    this.panel = vscode.window.createWebviewPanel(
      'codeNodes.graph',
      'Code Nodes Graph',
      { viewColumn: vscode.ViewColumn.Beside, preserveFocus: true },
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [
          vscode.Uri.joinPath(this.context.extensionUri, 'media'),
          vscode.Uri.joinPath(this.context.extensionUri, 'dist', 'media'),
        ],
      }
    );

    this.panel.webview.html = this.buildHtml(this.panel.webview);

    this.panel.webview.onDidReceiveMessage(async msg => {
      switch (msg.type) {

        case 'ready':
          // Load fresh settings from file before sending graph data
          this.settings = await readSettings();
          this.sendGraphData();
          break;

        case 'openNote':
          await this.openNote(msg.displayName as string);
          break;

        case 'saveForces':
          this.settings.forces = msg.forces as GraphForces;
          this.scheduleSave();
          break;

        case 'savePositions':
          this.settings.positions = msg.positions as GraphPositions;
          this.scheduleSave();
          break;

        case 'saveViewport':
          this.settings.viewport = msg.viewport as GraphViewport;
          this.scheduleSave();
          break;
      }
    });

    this.panel.onDidDispose(() => {
      this.panel = undefined;
      this.lastTopologyHash = '';
    });
  }

  refresh(): void {
    if (!this.panel) return;
    const data = this.noteGraph.getGraphData();
    const hash = this.noteGraph.getTopologyHash();

    if (hash !== this.lastTopologyHash) {
      this.lastTopologyHash = hash;
      this.panel.webview.postMessage({
        type: 'graphData',
        data,
        forces:         this.settings.forces,
        savedPositions: this.settings.positions,
        savedViewport:  this.settings.viewport,
      });
    } else {
      this.panel.webview.postMessage({ type: 'graphUpdate', data });
    }
  }

  private sendGraphData(): void {
    if (!this.panel) return;
    const data = this.noteGraph.getGraphData();
    this.lastTopologyHash = this.noteGraph.getTopologyHash();
    this.panel.webview.postMessage({
      type: 'graphData',
      data,
      forces:         this.settings.forces,
      savedPositions: this.settings.positions,
      savedViewport:  this.settings.viewport,
    });
  }

  /** Debounce file writes to 1.5 s so rapid slider moves / drags don't hammer the disk. */
  private scheduleSave(): void {
    if (this.saveTimer) clearTimeout(this.saveTimer);
    this.saveTimer = setTimeout(() => {
      writeSettings(this.settings).catch(err =>
        console.error('[Code Nodes] Failed to write graph_settings.jsonc:', err)
      );
    }, 1500);
  }

  private async openNote(displayName: string): Promise<void> {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    if (!workspaceFolder) {
      vscode.window.showErrorMessage(
        'Code Nodes: No workspace folder open. Please open a folder first.'
      );
      return;
    }

    const uri = vscode.Uri.joinPath(workspaceFolder.uri, `${displayName}.md`);

    try {
      await vscode.workspace.fs.stat(uri);
    } catch {
      await vscode.workspace.fs.writeFile(uri, new Uint8Array());
    }

    await vscode.commands.executeCommand(
      'vscode.openWith',
      uri,
      'codeNodes.markdownEditor',
      vscode.ViewColumn.One
    );
  }

  private buildHtml(webview: vscode.Webview): string {
    const nonce = getNonce();

    const vendorUri = webview.asWebviewUri(
      vscode.Uri.joinPath(this.context.extensionUri, 'dist', 'media', 'graph', 'vendor.js')
    );
    const graphJsUri = webview.asWebviewUri(
      vscode.Uri.joinPath(this.context.extensionUri, 'media', 'graph', 'graph.js')
    );
    const graphCssUri = webview.asWebviewUri(
      vscode.Uri.joinPath(this.context.extensionUri, 'media', 'graph', 'graph.css')
    );

    return /* html */ `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'none';
                 script-src 'nonce-${nonce}';
                 style-src ${webview.cspSource} 'unsafe-inline';">
  <link rel="stylesheet" href="${graphCssUri}">
  <title>Code Nodes Graph</title>
</head>
<body>
  <div id="cy-container"></div>
  <div id="legend">
    <span class="dot active"></span>Open
    <span class="dot exists"></span>Exists
    <span class="dot ghost"></span>Ghost
  </div>
  <div id="controls">
    <button id="fit-btn" title="Fit graph to window">⊞ Fit</button>
    <label>Repulsion
      <input type="range" id="repulsion" min="100" max="20000" step="100">
      <span class="val" id="repulsion-val"></span>
    </label>
    <label>Gravity
      <input type="range" id="gravity" min="0.01" max="1.0" step="0.01">
      <span class="val" id="gravity-val"></span>
    </label>
    <label>Edge Length
      <input type="range" id="edgeLength" min="30" max="600" step="10">
      <span class="val" id="edgeLength-val"></span>
    </label>
    <label title="How much nodes move when re-settling (0 = frozen, 1 = full recompute)">Energy
      <input type="range" id="damping" min="0.1" max="1.0" step="0.05">
      <span class="val" id="damping-val"></span>
    </label>
  </div>
  <script nonce="${nonce}" src="${vendorUri}"></script>
  <script nonce="${nonce}" src="${graphJsUri}"></script>
</body>
</html>`;
  }
}
